#If user gives varible values, first it is picking in this order
#1.CMD,2.Task,3.File,4.prompt,5.play,6.inventory,7.roles
- name: variables from PLAY level
  hosts: localhost
  vars_prompt:
    - name: PERSON
      prompt: please enter your PERSON
      private: false #user can see what they are entering
    - name: WISHES
      prompt: please enter your WISHES
      private: false #user can't see what they are entering
  vars_files:
    - variables.yaml
  vars:
    PERSON: "Chandra_Var from Play"
    WISHES: "Morning_Var from Play"
  tasks:
    - name: check variables
      vars:
        PERSON: "Chandra_Var from task"
        WISHES: "Morning_Var from task"
      ansible.builtin.debug:
        msg: "Hello {{PERSON}},Good {{WISHES}}!"
