#If user gives varible values, first it is picking in this order
#1.CMD,2.Task,3.File,4.prompt,5.play,6.inventory,7.roles(discuss later)
- name: variables from PLAY level
  hosts: localhost
  vars_prompt:
    - name: PERSON
      prompt: please enter your PERSON
      private: false #user can see what they are entering
    - name: WISHES
      prompt: please enter your WISHES
      private: false #user can't see what they are entering
  vars_files:
    - variables.yaml
  vars:
    PERSON: "5.Chandra_Var from Play"
    WISHES: "5.Morning_Var from Play"
  tasks:
    - name: check variables
      vars:
        PERSON: "2.Chandra_Var from task"
        WISHES: "2.Morning_Var from task"
      ansible.builtin.debug:
        msg: "Hello {{PERSON}},Good {{WISHES}}!"
