- name: Install NGINX
  hosts: localhost
  become: yes
  tasks:
    - name: Install NGINX on Red Hat
      yum:
        name: nginx
        state: present
      when: ansible_os_family == "RedHat" or ansible_os_family == "Suse"
