- name: Install Softwares # Playbook name
  hosts: localhost # Target hosts for the playbook
  become: yes
  vars: # Variables used in the playbook
    packages:
      - name: nginx
        required: True
      - name: mysql
        required: True
      - name: apache
        required: False
  tasks: # Tasks to be executed on the target hosts
    - name: Install packages on RedHat # Task to install packages on redHat
      yum:
        name: "{{ item.name }}"
        state: present
      # Loop over the packages variable
      loop: "{{ packages }}"
      # Install only if required property is set to true
      when: item.required == True
